/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "primary-container": "#131b2e",
        "on-secondary-container": "#fefcff",
        "tertiary": "#000000",
        "outline": "#76777d",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#002113",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#dae2fd",
        "surface-container": "#eceef0",
        "outline-variant": "#c6c6cd",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "primary": "#000000",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-container": "#2170e4",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#004395",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#4edea3",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#001a42",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed": "#002113",
        "background": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45464d",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#009668",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#d8e2ff",
        "secondary": "#0058be"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sidebar-width": "260px",
        "sm": "12px",
        "gutter": "24px",
        "lg": "40px",
        "xs": "4px",
        "md": "24px",
        "base": "8px",
        "xl": "64px"
      },
      fontFamily: {
        "numeric-data": ["Manrope"],
        "display": ["Manrope"],
        "h2": ["Manrope"],
        "h3": ["Manrope"],
        "body-md": ["Manrope"],
        "body-sm": ["Manrope"],
        "label-caps": ["Manrope"],
        "body-lg": ["Manrope"],
        "h1": ["Manrope"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@container-queries/tailwindcss'),
  ],
}
